import {ISuccessStoryShareProps} from '@/sections/detail-settlement-programs/success-story-share'

const successStoryShare: ISuccessStoryShareProps = {
  title: 'Chia sẻ câu chuyện thành công',
  items: [
    {
      name: 'Anh Nguyễn Văn Minh 1',
      review:
        'Từ một nhân viên văn phòng tại Việt Nam, tôi đã trở thành chủ một nhà hàng Việt ở Toronto.',
      link: '#',
      image: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/d-banner-settlement-programs.png',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
    {
      name: 'Anh Nguyễn Văn Minh',
      review:
        'Từ một nhân viên văn phòng tại Việt Nam, tôi đã trở thành chủ một nhà hàng Việt ở Toronto.',
      link: '#',
      image: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/d-banner-settlement-programs.png',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
    {
      name: 'Anh Nguyễn Văn Minh',
      review:
        'Từ một nhân viên văn phòng tại Việt Nam, tôi đã trở thành chủ một nhà hàng Việt ở Toronto.',
      link: '#',
      image: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/d-banner-settlement-programs.png',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
  ],
}

export default successStoryShare
