/* eslint-disable @typescript-eslint/no-explicit-any */
import type {Metadata} from 'next'
import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'HomePage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return children
}
