/* eslint-disable @typescript-eslint/no-explicit-any */
import type {Metadata} from 'next'
import localFont from 'next/font/local'
import '@/app/globals.css'
import {Toaster} from 'sonner'
import Header from '@/layout/header'
import Footer from '@/layout/footer'
import {Inter} from 'next/font/google'
import fetchData from '@/fetch/fetchData'
import Providers from '@/components/proccessBar'
const inter = Inter({subsets: ['latin']})
const optima = localFont({
  src: [
    {
      path: './fonts/SVN-Optima-Regular.ttf',
      weight: 'normal',
      style: 'normal',
    },
    {
      path: './fonts/SVN-Optima-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/SVN-Optima-DemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-optima', // Đặt biến CSS cho font Reckless
})
export const metadata: Metadata = {
  title: 'HomePage',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const requestFooter = {
    api: '/footer-options?acf_format=standard',
    option: {
      next  : { revalidate: 60 },
    },
  }
  const requestHeader = {
    api: '/header-options?acf_format=standard',
    option: {
      next  : { revalidate: 60 },
    },
  }
  const [dataFooter, dataHeader] = await Promise.all([
    fetchData(requestFooter),
    fetchData(requestHeader),
  ])
  return (
    <html lang='en'>
      <body className={` ${optima.variable} ${inter.className} antialiased`}>
        <Header
          data={dataHeader?.data}
          dataFooter={dataFooter.data}
        />

        <Providers>{children}</Providers>
        <Toaster
          theme='light'
          richColors
          position='bottom-right'
          closeButton
          duration={4000}
          expand
        />
        <Footer dataFooter={dataFooter?.data} />
      </body>
    </html>
  )
}
