import {IProcessStepsProps} from '@/sections/detail-settlement-programs/process-steps'

const processSteps: IProcessStepsProps = {
  title: 'Quy trình hồ sơ',
  description:
    'Chúng tôi hướng dẫn bạn từng bước để hoàn thành chương trình định cư một cách nhanh chóng và hiệu quả. Hãy để iCanfield đồng hành cùng bạn từ khâu chuẩn bị đến khi đặt chân đến vùng đất mới.',
  steps: [
    {
      title: 'Tư vấn và đánh giá hồ sơ',
      description:
        'Chúng tôi hướng dẫn bạn từng bước để hoàn thành chương trình định cư một cách nhanh chóng và hiệu quả. Hãy để iCanfield đồng hành cùng bạn từ khâu chuẩn bị đến khi đặt chân đến vùng đất mới.',
      image: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/d-process-steps-item.webp',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
    {
      title: 'Chuẩn bị và nộp hồ sơ',
      description:
        'Chúng tôi hướng dẫn bạn từng bước để hoàn thành chương trình định cư một cách nhanh chóng và hiệu quả. Hãy để iCanfield đồng hành cùng bạn từ khâu chuẩn bị đến khi đặt chân đến vùng đất mới.',
      image: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/d-process-steps-item.webp',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
    {
      title: 'Theo dõi tiến trình xét duyệt',
      description:
        'Chúng tôi hướng dẫn bạn từng bước để hoàn thành chương trình định cư một cách nhanh chóng và hiệu quả. Hãy để iCanfield đồng hành cùng bạn từ khâu chuẩn bị đến khi đặt chân đến vùng đất mới.',
      image: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/d-process-steps-item.webp',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
    {
      title: 'Nhận visa và chuẩn bị định cư',
      description:
        'Chúng tôi hướng dẫn bạn từng bước để hoàn thành chương trình định cư một cách nhanh chóng và hiệu quả. Hãy để iCanfield đồng hành cùng bạn từ khâu chuẩn bị đến khi đặt chân đến vùng đất mới.',
      image: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/d-process-steps-item.webp',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
  ],
}

export default processSteps
