import {IProgramEligibilityProps} from '@/sections/detail-settlement-programs/program-eligibility'

const programEligibility: IProgramEligibilityProps = {
  title: 'Điều kiện tham gia chương trình',
  description:
    'Icanfield mở ra cánh cửa đến cuộc sống chất lượng, cơ hội phát triển toàn diện và môi trường lý tưởng cho cả gia đình bạn. ',
  background: {
    ID: 1,
    id: 1,
    title: 'string',
    filename: 'string',
    filesize: 1,
    url: '/imgs/detail-settlement-programs/d-program-eligibility-bg.webp',
    link: 'string',
    alt: 'string',
    author: 'string',
    description: 'string',
    caption: 'string',
    name: 'string',
    status: 'string',
    uploaded_to: 1000,
    date: 'string',
    modified: 'string',
    menu_order: 1000,
    mime_type: 'string',
    type: 'string',
    subtype: 'string',
    icon: 'string',
    width: 1000,
    height: 1000,
  },
  items: [
    {
      title: 'Số tiền đầu tư',
      description:
        'Tối thiểu 800.000 USD cho dự án ở vùng TEA hoặc 1.050.000 USD ở khu vực khác.',
      icon: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/program-eligibility-icon.svg',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
    {
      title: 'Đối tượng đầu tư',
      description:
        'Dự án phải tạo ra ít nhất 10 việc làm toàn thời gian cho lao động Mỹ, trung tâm vùng bảo trợ dự án EB-5 cần được cấp phép và nộp hồ sơ lên USCIS.',
      icon: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/program-eligibility-icon-1.svg',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
    {
      title: 'Yêu cầu đầu tư',
      description:
        'Dự án phải tạo ra ít nhất 10 việc làm toàn thời gian cho lao động Mỹ, trung tâm vùng bảo trợ dự án EB-5 cần được cấp phép và nộp hồ sơ lên USCIS.',
      icon: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/program-eligibility-icon-2.svg',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
    {
      title: 'Chứng minh tài chính',
      description:
        'Dự án phải tạo ra ít nhất 10 việc làm toàn thời gian cho lao động Mỹ, trung tâm vùng bảo trợ dự án EB-5 cần được cấp phép và nộp hồ sơ lên USCIS.',
      icon: {
        ID: 1,
        id: 1,
        title: 'string',
        filename: 'string',
        filesize: 1,
        url: '/imgs/detail-settlement-programs/program-eligibility-icon-3.svg',
        link: 'string',
        alt: 'string',
        author: 'string',
        description: 'string',
        caption: 'string',
        name: 'string',
        status: 'string',
        uploaded_to: 1000,
        date: 'string',
        modified: 'string',
        menu_order: 1000,
        mime_type: 'string',
        type: 'string',
        subtype: 'string',
        icon: 'string',
        width: 1000,
        height: 1000,
      },
    },
  ],
}
export default programEligibility
