/* eslint-disable @typescript-eslint/no-explicit-any */
import type {Metadata} from 'next'
import localFont from 'next/font/local'
import '../globals.css'
//
import {NextIntlClientProvider} from 'next-intl'
import {getMessages, setRequestLocale} from 'next-intl/server'
import {notFound} from 'next/navigation'
import {routing} from '@/i18n/routing'
import {Toaster} from 'sonner'
//

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//
export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}))
}

export default async function RootLayout({
  children,
  params: {locale},
}: Readonly<{
  children: React.ReactNode
  params: {locale: string}
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound()
  }

  // Enable static rendering
  setRequestLocale(locale)

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body className={`antialiased`}>
        <NextIntlClientProvider messages={messages}>
          {children}
          <Toaster
            theme='light'
            richColors
            position='bottom-right'
            closeButton
            duration={4000}
            expand
          />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
