export const categories = [
  {
    id: 0,
    name: 'Tất cả',
    slug: 'all',
    taxonomy: 'all',
  },
  {
    id: 7,
    name: 'Bất động sản',
    slug: 'bat-dong-san',
    taxonomy: 'category',
  },
  {
    id: 4,
    name: 'Vùng công nghiệp',
    slug: 'vung-cong-nghiep',
    taxonomy: 'category',
  },
  {
    id: 3,
    name: 'Không gian công cộng',
    slug: 'khong-gian-cong-cong',
    taxonomy: 'category',
  },
]
export const fakeDataProjects = {
  data: [
    {
      link: '/du-an-hudson-yards',
      name: 'Dự án Hudson Yards',
      location: 'New York, Mỹ',
      type: 'TEA Vùng nông thôn',
      scale: '800 triệu USD',
      ub5CapitalRatio: '12.5%',
      jobsCreatedRatio: '522%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
    {
      link: '/du-an-golden-gate-bridge',
      name: 'Dự án Golden Gate Bridge',
      location: 'San Francisco, Mỹ',
      type: 'TEA Vùng nông thôn',
      scale: '1 tỷ USD',
      ub5CapitalRatio: '15%',
      jobsCreatedRatio: '600%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
    {
      link: '/du-an-central-park-tower',
      name: 'Dự án Central Park Tower',
      location: 'New York, Mỹ',
      type: 'TEA Vùng đô thị',
      scale: '3 tỷ USD',
      ub5CapitalRatio: '10%',
      jobsCreatedRatio: '480%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
    {
      link: '/du-an-luxury-condo',
      name: 'Dự án Luxury Condo',
      location: 'Los Angeles, Mỹ',
      type: 'TEA Vùng đô thị',
      scale: '750 triệu USD',
      ub5CapitalRatio: '20%',
      jobsCreatedRatio: '550%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
    {
      link: '/du-an-green-valley',
      name: 'Dự án Green Valley',
      location: 'Seattle, Mỹ',
      type: 'TEA Vùng nông thôn',
      scale: '1.5 tỷ USD',
      ub5CapitalRatio: '18%',
      jobsCreatedRatio: '580%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
    {
      link: '/du-an-ocean-breeze',
      name: 'Dự án Ocean Breeze',
      location: 'Miami, Mỹ',
      type: 'TEA Vùng đô thị',
      scale: '900 triệu USD',
      ub5CapitalRatio: '14%',
      jobsCreatedRatio: '510%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
    {
      link: '/du-an-forest-haven',
      name: 'Dự án Forest Haven',
      location: 'Oregon, Mỹ',
      type: 'TEA Vùng nông thôn',
      scale: '600 triệu USD',
      ub5CapitalRatio: '16%',
      jobsCreatedRatio: '570%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
    {
      link: '/du-an-skyline-tower',
      name: 'Dự án Skyline Tower',
      location: 'Chicago, Mỹ',
      type: 'TEA Vùng đô thị',
      scale: '2 tỷ USD',
      ub5CapitalRatio: '12%',
      jobsCreatedRatio: '495%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
    {
      link: '/du-an-lake-view-resort',
      name: 'Dự án Lake View Resort',
      location: 'Minnesota, Mỹ',
      type: 'TEA Vùng nông thôn',
      scale: '850 triệu USD',
      ub5CapitalRatio: '17%',
      jobsCreatedRatio: '560%',
      image: {
        alt: 'alt text',
        src: '/imgs/EB5/Pioneering-values/items.webp',
      },
    },
  ],
  totalPages: 3,
}
